apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Porta do Service (interna ao cluster)
      targetPort: 80 # Porta do contêiner
  type: NodePort # Expor o serviço para fora do cluster

